# Site settings
title: Elizar Pepino
email: jupenz@gmail.com
greetings: Elizar Pepino
description: > # this means to ignore newlines until "baseurl:"
  A self-taught, pragmatic programmer, a coffee lover, and an occasional pixel pusher. Polyglot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://elizarpepino.com" # the base hostname & protocol for your site
twitter_username: jupenz
github_username:  elizar
dribbble_username:  elizarpepino
permalink: /:title

# Build settings
markdown: kramdown
