# Site settings
title: SUAVE
email: suave-developers@lists.stanford.edu
greetings: SUAVE
description: > # this means to ignore newlines until "baseurl:"
  A multi-fidelity conceptual design environment. Its purpose is to credibly produce conceptual-level design conclusions for future aircraft incorporating advanced technologies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://suavecode.github.io/" # the base hostname & protocol for your site
github_username:  suavecode
permalink: /:title

# Build settings
markdown: kramdown
